[general]
# geometry: x,y, where x - number of rows, y - number of columns
geometry: 1,2
outputfile: movie.mp4
fmin: 
fmax: 
# if dir left emtpy, then current dir
dir:
step: 1
ncpu: 1
namelist: driving.nml
cbar_width: 0.1
insert: 0

[map01]
kind: dens
proj: 1
logscale: True
min: 0.1
max: 1e3
bar: 20 pc
timer: True
label: Density [H/cc]
labelcolor: white
colormap: inferno
colorbar: True
sink: False
true_sink: True
streamlines: False
fontsize: 20



[map02]
kind: temp
proj: 1
logscale: True
min: 1e2
max: 1e6
bar: 20 pc
timer: True
label: Temperature [K]
labelcolor: white
colormap: Reds_r
colorbar: True
sink: False
true_sink: True
streamlines: False
fontsize: 20



[map03]
kind: dens
proj: 2
logscale: True
min: 0.1
max: 1e3
bar: 100 pc
timer: True
label: Density [H/cc]
labelcolor: white
colormap: inferno
colorbar: True
sink: False
true_sink: True
streamlines: False
fontsize: 20



[map04]
kind: temp
proj: 2
logscale: True
min: 1e2
max: 1e6
bar: 100 pc
timer: True
label: Temperature [K]
labelcolor: white
colormap: Reds_r
colorbar: True
sink: False
true_sink: True
streamlines: False
fontsize: 20
